### ISSUE TITLE
Change processing of URL inputs in bulk upload

### ISSUE THREAD

**Issue by noah-schechter** [milesmcc/atlos#101]
If a user uploads a CSV with multiple empty source columns, the Atlos bot's comment treats each empty source cell as a URL: 
<img width="751" alt="Screen Shot 2022-06-23 at 23 20 20" src="https://user-images.githubusercontent.com/100018299/175477143-c80f33d4-09b7-4238-a2a8-1e300384064c.png">

Could you make sure we're checking if the URL field is empty before treating the string as a source URL to be archived?

**Comment by milesmcc** [comment]
Hah, this is a hilarious bug.
