### ISSUE TITLE
Bulk upload interface location

### ISSUE THREAD

**Issue by noah-schechter** [milesmcc/atlos#102]
Bulk upload UI is looking great. I've divided a few small UI ideas each into their own issue, starting with this one.

I'm not sure where I land here, but what if we moved bulk upload from Adminland to the Upload New Media page? And placed a button similar to the one we have on the top right of Adminland on the Upload New Media page? I'm not sure if that makes it easier to find, but I feel like it's conceptually consistent. (This button would still only be visible to admins)

**Comment by milesmcc** [comment]
Good idea. Perhaps we even have it in _both_ places? Like, some kind of admin-gated button on the new page that takes them to bulk upload (in Adminland) when they click it?

**Comment by milesmcc** [comment]
<img width="672" alt="image" src="https://user-images.githubusercontent.com/3037552/177479780-e57d2489-5d1b-4a0e-ad1b-f046e741a9e7.png">
