### ISSUE TITLE
Should tagging users effectively subscribe them to incidents?

### ISSUE THREAD

**Issue by noah-schechter** [milesmcc/atlos#126]
When I (@alt_noah) tagged @noah in an incident @noah was not subscribed to, @noah's notifications displayed all previous updates to the incident, not just the update in which @noah was tagged.

Is this intentional? If so, should we also formally indicate that the tagged users has been subscribed? Or is this odd because it allows users to subscribe each other to incidents?

**Comment by milesmcc** [comment]
It's because `alt_noah` contains `noah` so everything each user did was shown to the other, I think. Should be fixed.
