### ISSUE TITLE
Account confirmation email isn't working

### ISSUE THREAD

**Issue by noah-schechter** [milesmcc/atlos#15]
When I created my second account, I received an email asking me to confirm the account. The link seems to be broken; I received an empty response error (see the picture below). 

Also, I'm not sure if you implemented/pushed email confirmations after I created my first account, but I never got an email asking me to confirm the first account.

<img width="1288" alt="Screen Shot 2022-05-03 at 01 38 42" src="https://user-images.githubusercontent.com/100018299/166425918-cb96d635-962f-467d-ba30-47c9764eb45b.png">

**Comment by milesmcc** [comment]
fixed
