### ISSUE TITLE
Warning about 'None'/'Indeterminate' should be visible even when dropdown is opened.

### ISSUE THREAD

**Issue by noah-schechter** [milesmcc/atlos#2]
This is a design choice, not a bug, but the dropdown menu currently obscures the warning that 'indeterminate' can't be selected with other options, so the warning is only visible once the dropdown is closed. If you think this is ok, feel free to just close the issue without changes.

https://user-images.githubusercontent.com/100018299/166380546-1c3a0ce1-205b-4a69-94cf-413f352bbc3b.mov

**Comment by milesmcc** [comment]
Our options are to either move the warning above, which might look weird, or make the dropdown open upwards, which is also a bit weird. I'm inclined to just bite the bullet here...

**Comment by noah-schechter** [comment]
Maybe we should try moving the warning above? But if it looks bad we can keep it as is.
