### ISSUE TITLE
Remove blank link warning on Upload New Media page

### ISSUE THREAD

**Issue by noah-schechter** [milesmcc/atlos#32]
On the second Upload New Media page, the aside warning about blank fields (red) is pretty prominent, so I think it makes the  'can't be blank' message (blue) under the link entry field redundant. Can we remove the 'can't be blank' message?

**Comment by milesmcc** [comment]
Not easily, unfortunately. The "can't be blank" message is a more general error message, and it's not easy to remove independent of the larger error message. Maybe the redundancy is good?

**Comment by noah-schechter** [comment]
Ok, no worries. Could you change 'can't be blank' to 'Provide a source link to demonstrate the media's authenticity.'? Or is it not possible to specialize error messages for each instance either?

**Comment by milesmcc** [comment]
Sure we can do that
