### ISSUE TITLE
Should users be able to comment an image without attached text?

### ISSUE THREAD

**Issue by noah-schechter** [milesmcc/atlos#34]
I'm not entirely sure about this one but perhaps users should be able to comment an image with no attached text. We currently require text input independent of attached images. Your thoughts? 

<img width="830" alt="Screen Shot 2022-05-03 at 18 33 37" src="https://user-images.githubusercontent.com/100018299/166612375-c50a7a26-48f2-44b2-becc-8584044fd398.png">

**Comment by milesmcc** [comment]
Hmm, tbh I lean towards not letting them upload message free comments. I feel like it's helpful to have some kind of explanation?

**Comment by noah-schechter** [comment]
I guess I'm thinking about a situation in which a user posted a comment and forgot to attach photos, and now wants to include a photo in a subsequent comment. In that case, I don't think we would want to restrict their ability to post just attachments, especially given that they can't delete or edit comments. Maybe I'm missing something—what do you see as the downside to a more flexible comment interface?

**Comment by milesmcc** [comment]
I feel like in that case, they could say "Forgot to attach photos—here they are." Allowing comments without content might make searching weird/difficult down the line — I also wonder whether it helps promote a norm of always providing context.

**Comment by noah-schechter** [comment]
Sounds great. Closing this one.
