### ISSUE TITLE
Change text of confirmation email

### ISSUE THREAD

**Issue by noah-schechter** [milesmcc/atlos#37]
Can we change the confirmation email copy? I'm guessing this is harder than changing platform copy. If so, it's probably not worth your time.

Anyway, if it's a quick fix can you change the confirmation email to: 
"Hi [username],

Thanks for joining the Atlos researcher community! 

To confirm your account, visit the URL below:
[URL].

Best,
The Atlos Team

_If you didn't create an Atlos account, feel free to ignore this email._"

**Comment by milesmcc** [comment]
Slight difference because we can't do italics, wdyt?

    Hi #{user.email},

    Thanks for joining the Atlos researcher community!

    You can confirm your account by visiting the URL below:

    #{url}

    If you didn't create an account with us, please ignore this message.

    Thanks,
    The Atlos Team

**Comment by noah-schechter** [comment]
That works! Could we do "Best, The Atlos Team" bc we say thanks at the beginning?
