### ISSUE TITLE
Hide graphic media even on media page

### ISSUE THREAD

**Issue by noah-schechter** [milesmcc/atlos#41]
Can we hide graphic media even on the media page? So that you have to toggle to view the media in the same way you would toggle color? The idea here is that a researcher would be able catalog media without having to see it on the right side of their screen the whole time. Thanks!

**Comment by milesmcc** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/3037552/177927590-9ee30eaf-693f-4de2-b4a4-7153b9f9cb13.png">
