### ISSUE TITLE
Media card exit button on map alignment

### ISSUE THREAD

**Issue by noah-schechter** [milesmcc/atlos#59]
I think the exit button is a bit misaligned. Maybe it's fine but I guess it could be higher and a bit more to the left? 
<img width="783" alt="Screen Shot 2022-05-18 at 00 27 39" src="https://user-images.githubusercontent.com/100018299/169359770-6979e082-8adf-45e1-ab3c-d6d1dfa4d200.png">

**Comment by noah-schechter** [comment]
Decided this isn't an issue.

**Comment by milesmcc** [comment]
removed
