### ISSUE TITLE
Should a message be required when claiming media?

### ISSUE THREAD

**Issue by milesmcc** [milesmcc/atlos#60]
We are moving to require a message for updating the `flag` attribute — "help needed," "second opinion needed," etc. Requiring an explanation makes sense for these attributes, but what about "claimed"?

**Comment by noah-schechter** [comment]
I don't think so, unless you're worried that it would get too confusing if only some of these attributes require the extra step. If that's not a concern, claiming shouldn't require an explanation; I don't think there's much to explain.
