### ISSUE TITLE
Domain and site structure

### ISSUE THREAD

**Issue by noah-schechter** [milesmcc/atlos#88]
To be clear: I'm thinking about all of this cosmetically; if there are technical issues that make one structure easier than the other, let's stick to solving those problems first. 

Ideally, atlos.org would be the home page (map) of the main instance of Atlos for signed-in users. Then we wouldn't need a separate app.atlos.org. For non-authenticated visitors, our current landing page would stay at atlos.org and we'd stick a login button at the top right. Would that work and do you think this is best?

**Comment by milesmcc** [comment]
Yeah, I think this could work. Where would Bellingcat's instance go?

**Comment by noah-schechter** [comment]
Perhaps bellingcat.atlos.org? (We could go with gap.atlos.org but that might be too small in scope.) The issue here is that if I'm a GAP volunteer and navigate to atlos.org and try to sign in, I wouldn't be signing in to the right instance. I guess on the sign in page we could include a 'If you're working with Bellingcat, click here to sign in to Atlos,' or something of the sort?

**Comment by milesmcc** [comment]
I think this is the right way going forward, but right now it's a bit difficult to get the landing page to play nice with the platform. Maybe for now we do `platform.atlos.org` (for big Atlos) and `bellingcat.atlos.org` (for GAP Atlos)?

**Comment by milesmcc** [comment]
Not too much trouble to change this down the line, for what it's worth.
